spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: marcoadp
      password: santos2023


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
