spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ${EUREKA_NAME}
      password: ${EUREKA_PWD}


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
